### ISSUE TITLE
New Selector syntax

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Game-Of-Life-SpriteKit-Swift#3]
Not sure how you feel about this, Xcode suggests a newer selector syntax: 

let callMethod = SKAction.performSelector("stepSimulation", onTarget: self)

becomes: 

let callMethod = SKAction.performSelector(#selector(GameScene.stepSimulation), onTarget: self)

Either works.

**Comment by cocojoe** [comment]
If this was compatible with Xcode 7.2.1 then yes it would make sense to use the updated syntax.  As it stands the game projects are for Xcode 7.2.1 due to issues with SpriteKit in Xcode 7.3+.  If this situation changes then yes it can be updated, although it wouldn't cause any student issues as it's a warning with an auto-correct. Thx
